# Generated by Django 2.2 on 2020-10-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='название университета'),
        ),
    ]
